name: Deploy to EC2

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd vite
          npm install

      - name: Build project
        run: |
          cd vite
          npm run build

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          # Save the private key to a file
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # Sync files to the EC2 instance
          rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./admin_panel_ekarigar/vite/dist/ $USERNAME@$HOST:/home/ubuntu/admin_panel_ekarigar/vite/

          # Reload NGINX on the server
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$HOST "sudo systemctl reload nginx"
